# Generated by Django 4.1.5 on 2023-03-06 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_length', models.CharField(choices=[('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33')], default='28', max_length=20)),
                ('first_phase_length', models.CharField(choices=[('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='5', max_length=20)),
                ('second_phase_length', models.IntegerField(default=8)),
                ('third_phase_length', models.IntegerField(default=1)),
                ('start_time', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
