# Generated by Django 4.1.5 on 2023-03-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_calendar', '0002_remove_usercalendar_start_time_usercalendardate'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercalendardate',
            name='first_phase_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercalendardate',
            name='fourth_phase_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercalendardate',
            name='fourth_phase_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercalendardate',
            name='second_phase_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercalendardate',
            name='second_phase_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercalendardate',
            name='third_phase',
            field=models.DateField(blank=True, null=True),
        ),
    ]
