# Generated by Django 4.1.5 on 2023-03-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_calendar', '0006_uniquetextshare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniquetextshare',
            name='unique_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
