# Generated by Django 4.1.5 on 2023-03-19 20:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentpost',
            name='text',
        ),
        migrations.AddField(
            model_name='commentpost',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commentpost',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
