# Generated by Django 4.1.5 on 2023-02-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary_image',
            field=models.ImageField(default=None, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='post',
            name='summary_text',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='text_image_1',
            field=models.ImageField(default=None, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='post',
            name='text_image_2',
            field=models.ImageField(default=None, upload_to='blog/static/imagine/'),
        ),
    ]
