# Generated by Django 4.1.5 on 2023-02-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_summary_image_post_summary_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='summary_image',
            field=models.ImageField(default=None, upload_to='blog/static/imagine/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_image_1',
            field=models.ImageField(default=None, upload_to='blog/static/imagine/'),
        ),
    ]
