# Generated by Django 4.1.5 on 2023-02-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_summary_image_alter_post_text_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='summary_image',
            field=models.ImageField(default=None, upload_to='blog/image/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_image_1',
            field=models.ImageField(default=None, upload_to='blog/image/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_image_2',
            field=models.ImageField(default=None, upload_to='blog/image/'),
        ),
    ]
