# Generated by Django 4.1.5 on 2023-02-19 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text_image_1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text_image_2',
        ),
    ]
